### PR TITLE
Fix view sample id issue. Fix #475

### LINKED ISSUE #475: Raycasting acts odd with large axis ranges
When there is a large range between smallest and largest values on an axis, the raycaster will sometimes be off and not acknowledge a click.

### PR DESCRIPTION
**Pull request by squirrelo**

### CODE REVIEW

File: emperor/support_files/js/sceneplotview3d.js [hunk 1]
```diff
@@ -62,15 +62,16 @@ define([
     this._axisLabelPrefix = 'emperor-axis-label-';
 
     // Set up the camera
-    // Note: if we change the near parameter to something smaller than this
-    // the raytracing will not work as expected.
+    var max = _.max(decViews.scatter.decomp.dimensionRanges.max);
+    var frontFrust = _.min([max * 0.001, 1]);
```
Comment (ElDeveloper) [inline emperor/support_files/js/sceneplotview3d.js]: 👍 I like this!

**Comment by ElDeveloper** [comment]
Thanks @squirrelo
