### PR TITLE
BUG:Fixes a color distortion for flat-facing geometries

### LINKED ISSUE #544: sample shape causes color to change
I am really enjoying this new feature.

But non-sphere shapes cause the color to lighten. e.g., in the attached plot there should be 5 colors (I pasted the color key below).

Also, just a general comment — non-sphere shapes don't look great in 3D, as only the spheres have good depth. Shape selection + [2D plots](https://github.com/biocore/emperor/issues/303) = better choices.

image
image

### PR DESCRIPTION
**Pull request by ElDeveloper**
Geometries that are flat-facing would suffer from color distortion. To
fix this, I've added a small amount of rotation to those geometries. And
included a few new geometries.

Fixes #544

### CODE REVIEW

**Comment by ElDeveloper** [comment]
The screenshots below show examples of a bunch of different geometries and how the colors are much more homogeneous now:

# New
screen shot 2017-11-27 at 11 45 58 pm

# Old
screen shot 2017-11-27 at 11 48 58 pm

**Comment by ElDeveloper** [comment]
Tests are failing because of a new release of flake8, merge #626 first.

File: emperor/support_files/js/shapes.js [hunk 1]
```diff
@@ -3,16 +3,17 @@
...
 
-  var shapes = [SPHERE, CUBE, CONE, ICOSAHEDRON, CYLINDER];
+  var shapes = [SPHERE, OCTAHEDRON, CONE, CYLINDER, RING, SQUARE, ICOSAHEDRON];
 
   /**
    *
    * Return a correctly sized geometry that matches the plotting space
    *
-   * @param {string} shapeName One of 'Sphere', 'Cube', 'Cone', 'Icosahedron'
+   * @param {string} shapeName One of 'Sphere', 'Square', 'Cone', 'Icosahedron'
```
Comment (antgonza) [inline emperor/support_files/js/shapes.js]: Here you are missing 2, right? OCTAHEDRON and RING
