### PR TITLE
BUG: Hide edges when hiding visible samples

### LINKED ISSUE #193: able to hide both dots and edges of a given group in a procrustes plot
currently only dots can be hidden, leaving their edges on the plot. It would be great to provide the ability to hide both of them to keep the rest of figure visually clean.

### PR DESCRIPTION
**Pull request by ElDeveloper**
For procrustes plots edges were not being hidden when samples in it were. Demo:

procrustes-bug

Fixes #193

### CODE REVIEW

File: emperor/support_files/js/view.js [hunk 1]
```diff
@@ -414,5 +435,70 @@ DecompositionView.prototype.setCategory = function(attributes,
...
+
+  hideAll = plottables === undefined;
+
+  this.decomp.edges.forEach(function(edge) {
+    u = edge[0];
+    v = edge[1];
+
+    if (hideAll ||
+        (plottables.indexOf(u) !== -1 || plottables.indexOf(v) !== -1)) {
+      positionsLeft[(j * 6)] = 0;
```
Comment (antgonza) [inline emperor/support_files/js/view.js]: The 1->5 sounds/looks like a variable or something like that ... or why 5?

Comment (antgonza) [reply emperor/support_files/js/view.js]: Thus, this is a global parameter defined by BufferGeometry and if changed this will change, right? Therefore, should we have it encapsulated somehow (method?) so we don't need to change multiple places if we move to something different? If the answer is yes and the changes are complex, opening an issue is fine.

Comment (ElDeveloper) [reply emperor/support_files/js/view.js]: Fair enough, I've created a wrapper method for these changes. 👍

**Comment by antgonza** [comment]
Great, thanks. Just to confirm, that kind of modification is not happening anywhere else in the code? What I mean, this new code can't be use somewhere else?

**Comment by ElDeveloper** [comment]
Just double checked and those are the only places where the
modifications are happening.
